# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kCuUaD4WPh1912vPEYFO0Fy4Hhu8ntb7Fy48qQO+jw52En3xYMchy+FgilO1+HYhoeaiPzFqYXbu+klTsI0AOI7QcVeovwNgFUvVagy9zvyc+6+5rNnfO9zZVlyfJACnT2/XJuXQEBCgWkYLnAF+0XKJb27LNrT6bv5KlgYFNYsAWqrqGCaz8/5z8GkBTf5Qvv8RMW7AvJxfegwfbl1+YSJ47HxWLatGoNTpUpT3ERDfzA778NxscGLKZ/T3Rb4Sq1c0viYFRIXS1w64A54fjgFP1yUpOxmJHHQyiJYopWsJgsRxqONSRXCQblyXuWn74MC2Q7J5Iq+9TRGV54/d6GCkZVEG6/S0qmQuAydVD6g1T6yVr1P95JyotdskKBLTxX+qSoRyi/5URvh/PwPa5Bk/mORfNmhQb7KC7kEwVomPghc1oMBXyUpDQkCfWfy6573gVfo0rD7umsfQkGEmaAwneHfH3hb4zw3VAM1ovfxEduRpD4/dGbDN6/KFF9gCkH3kTdGffdlCpwgFS9+rCeBBSkAtbji/o9LGQBFLqnwmvlOL4ccNGJiDb9TNqOpUXQ8/8hM1flTUv5/NiB7tw5ZSoyTMXUt/ASfb5Idgzvz36g9EiGH9NU6W4E7o9Re0ColxNOqC3ZLRJxW2tpaoZKyhb4M/HUhTQTJuxrRK3FA="


before_install:
    # Remove homebrew.
    - brew remove --force --ignore-dependencies $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
