travis:
  secure:
    BINSTAR_TOKEN: NDAUrjJiozCDAIBDdmRNYRCSiDxzYjk3j/QoK6fGwneXK5RLKWsFWag13QpZg1vvXbWEM7ezLrZAkoWStORaRQzD8mVY/P4en+X5Z6uUC5o9WzV2+OPrpZxiBMohmgsfmyllp3NnKdvWJXbtWU0KY879TNFABB4e1yMkOnoYu3L6kHwF1PylQt7nBh55hnnLkZRuqZaJSEOJH5Btuynmx2RnXa8tYvOB8FTFULqFMmW95CVajm6nSDMJxLccvwfChqgt2+gEFaxDYyIwy/DI2OIcA8sffLeIDK4TvD/AMWJtIKXEXKV3Yx4DKxfMa2RvXI+M7idDaa+0TpH9bY+QmfJDcxe9MiHS8K68/2I1gZ9d1bTyBI23GHWFH/BpkXJ5LQrvGF8kT49bOM1VTAwyNoW6kBRzN7UID/n8k80r4FUjpuIF7/RarJFwY5hDhqQ0cp33pz2NUitHvnLeNylyLFM4Bso81Ox/IvLklav5rzDM10OB4evJLAS+5OnsKzHSKknbDAKtZMK6XWuRbXBdByaU18HRSmdGvuUNQU5wFyPcY/9TC2WPUpKz+81fMwrNynDI7TGgZk/g7TxuEIs5aAl2V6/p0Y8igN7TbQbKfntH/7qJzaOwnDCYhq8RFvjYNUT92MrRvsufrHmNtR9ngBwjAdmHHCAItiat1YxF6t4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
