travis:
  secure:
    BINSTAR_TOKEN: kCuUaD4WPh1912vPEYFO0Fy4Hhu8ntb7Fy48qQO+jw52En3xYMchy+FgilO1+HYhoeaiPzFqYXbu+klTsI0AOI7QcVeovwNgFUvVagy9zvyc+6+5rNnfO9zZVlyfJACnT2/XJuXQEBCgWkYLnAF+0XKJb27LNrT6bv5KlgYFNYsAWqrqGCaz8/5z8GkBTf5Qvv8RMW7AvJxfegwfbl1+YSJ47HxWLatGoNTpUpT3ERDfzA778NxscGLKZ/T3Rb4Sq1c0viYFRIXS1w64A54fjgFP1yUpOxmJHHQyiJYopWsJgsRxqONSRXCQblyXuWn74MC2Q7J5Iq+9TRGV54/d6GCkZVEG6/S0qmQuAydVD6g1T6yVr1P95JyotdskKBLTxX+qSoRyi/5URvh/PwPa5Bk/mORfNmhQb7KC7kEwVomPghc1oMBXyUpDQkCfWfy6573gVfo0rD7umsfQkGEmaAwneHfH3hb4zw3VAM1ovfxEduRpD4/dGbDN6/KFF9gCkH3kTdGffdlCpwgFS9+rCeBBSkAtbji/o9LGQBFLqnwmvlOL4ccNGJiDb9TNqOpUXQ8/8hM1flTUv5/NiB7tw5ZSoyTMXUt/ASfb5Idgzvz36g9EiGH9NU6W4E7o9Re0ColxNOqC3ZLRJxW2tpaoZKyhb4M/HUhTQTJuxrRK3FA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
